-- Local-ize the expected global tables:
--
local common = ctgen__common
local assignments = ctgen__matrix_coeff_assignments


local function allGenerators(backendSpecifics, ctModelMetadata, resolvedMatrices, config)
    local transforms = {}
    for tf in python.iter(ctModelMetadata.transformsMetadata) do
      table.insert(transforms, tf)
    end
    local env = {
        ctrl = {
            variables  = config.variables,
        },
        ids = {
            varName      = config.internal.cached_value_identifier,
            sinVarName   = config.internal.cached_sinvalue_identifier,
            cosVarName   = config.internal.cached_cosvalue_identifier,
            this         = config.meta.this_obj_ref,
            varStateArgName = config.variables.status_formal_parameter,
            parameters   = config.parameters,
            transforms   = transforms,
        },
        meta = config.meta,
        python = python,
        common = common,
        date = os.date(),
        model_name = ctModelMetadata.name,
        ctModelMetadata = ctModelMetadata,
    }

local function modelConstants()
    local tpltext = [[
% This file was generated by the Octave backend of the CtGen tool.
% Generated on «date» from model "«model_name»".

classdef «className» < handle

properties (Constant = true)

% NOTE: due to a bug in Octave, I cannot define a constant with a reference to
% a previously defined one:
%   https://savannah.gnu.org/bugs/?65214
%   https://savannah.gnu.org/bugs/?52582
% Thus, be careful when you want to change the value of a constant: you will
% have to change also the argument of sin/cos (if applicable)

@for _, cc in ipairs(constants) do
    «varname(cc)» = «cc.value»;
@   for _, expr in ipairs(constantsExpressions[cc]) do
@       if expr.isRotation() then
    «ids.sinVarName(expr)» = sin(«cc.value»); % should be:  sin( «className».«varname(cc)» );
    «ids.cosVarName(expr)» = cos(«cc.value»); % should be:  cos( «className».«varname(cc)» );
@       else
@           if not expr.isIdentity() then
    «ids.varName(expr)» = «expr_code»;
@           end
@       end
@   end
@end

end

end % classdef «className»
]]
    local constants, constantsExpressions = common.python_unique_expressions_dict_to_tables( ctModelMetadata.constants )
    local env2 = {
        ctModelMetadata = ctModelMetadata,
        ids = env.ids,
        constants  = constants,
        constantsExpressions = constantsExpressions,
        className = config.meta.constants_class.class_name(ctModelMetadata),
        varname = config.model_property_to_varname,
        date = os.date(),
        model_name = ctModelMetadata.name,
    }
    return common.tpleval(tpltext, env2)
end

local function matrixFunction(matrixReprMeta)
   local tpltext = [[
% This file was generated by the Octave backend of the CtGen tool.
% Generated on «date» from model "«model_name»".

classdef «class.name» < handle

properties
    «class.members.constants»
@if tf.parametric then
    «ids.parameters.member_name» = struct();
@end
    «class.members.matrix» = zeros(«matrixReprMeta.rows()»,«matrixReprMeta.cols()»);
end

methods
function «ids.this» = «class.name»(«class.fargs.constants»)
    «ids.this».«class.members.constants» = «class.fargs.constants»;

@local access = ids.this .. '.' .. class.members.matrix
@for statement in statementsGenerator.constantCoefficientsAssignments(access) do
    «statement»;
@end

@if tf.parametric then
    % Initializes the parameters
@   local P = ids.parameters.member_name
@   for param, expressions in pairs(parameters) do
@       for i, expr in pairs(expressions) do
@           if expr.isRotation() then
    «ids.this».«P».«ids.sinVarName(expr)» = 0;
    «ids.this».«P».«ids.cosVarName(expr)» = 1;
@           else
    «ids.this».«P».«ids.varName(expr)» = 0;
@           end
@       end
@   end
@end
end

function «class.methods.update»(«ids.this», «ids.varStateArgName»)
@for var, expressions in pairs(variables) do
@   for k, expr in pairs(expressions) do
@       local codearg = expr.toCode( ctrl.variables.value_expression(var) )
@       if expr.isRotation() then
    «ids.sinVarName(expr)» = sin( «codearg» );
    «ids.cosVarName(expr)» = cos( «codearg» );
@       end
@   end
@end
@for statement in statementsGenerator.variableCoefficientsAssignments(access) do
    «statement»;
@end
end


@if varcount > 0 then
function «class.methods.update_explicit_vars»(«ids.this», «table.concat(varnames, ", ")»)
    @for var, _ in pairs(variables) do
    «ctrl.variables.value_expression(var)» = «var.name»;
    @end
    obj.«class.methods.update»(«ids.varStateArgName»);
@else
function «class.methods.update_explicit_vars»(«ids.this»)
    obj.«class.methods.update»([]);
@end
end

@if tf.parametric then
@   local P = ids.parameters.member_name
function «class.methods.update_parameters»(«ids.this», «table.concat(parnames, ", ")»)
@   for param, expressions in pairs(parameters) do
@       for i, expr in pairs(expressions) do
@           local codearg = expr.toCode( param.name )
@           if expr.isRotation() then
    «ids.this».«P».«ids.sinVarName(expr)» = sin( «codearg» );
    «ids.this».«P».«ids.cosVarName(expr)» = cos( «codearg» );
@           else
    «ids.this».«P».«ids.varName(expr)» = «codearg»;
@           end
@       end
@   end
end
@end

end

end

]]
    local ctMetadata = matrixReprMeta.ctMetadata
    local varnames = {}
    local varcount = 0
    for i,var in common.myiter(ctMetadata.vars) do
        table.insert(varnames, var.name)
        varcount = varcount + 1
    end
    local parnames = {}
    for i,par in common.myiter(ctMetadata.pars) do
        table.insert(parnames, par.name)
    end
    local statementsGen = assignments.getMatrixSpecificGenerators(
                backendSpecifics.languageSpecifics, matrixReprMeta,
                resolvedMatrices[ctMetadata.name])

    env.class = config.meta.tf_class
    env.class.name = config.meta.tf_class.class_name(matrixReprMeta)
    env.tf = ctMetadata
    env.parameters = common.python_dictOfSets_to_table( ctMetadata.pars )
    env.variables  = common.python_dictOfSets_to_table( ctMetadata.vars )
    env.varcount   = varcount
    env.matrixReprMeta = matrixReprMeta
    env.parnames = parnames
    env.varnames = varnames
    env.statementsGenerator = statementsGen

    return common.tpleval(tpltext, env)
end

return {
  matrixFunction = matrixFunction,
  modelConstants = modelConstants,
  tests = tests_generator(env) --a global, defined in tests_tpl.lua
}

end

return allGenerators
